name: "Dump Tags"
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: git fetch --prune --unshallow --tags
      
      - name: Hash
        run: git rev-parse HEAD
        
      - name: Dump
        run: git tag
